import { Browser } from "@/components/apps/Browser";
import Calculator from "@/components/apps/Calculator";
import Camera from "@/components/apps/Camera";
import Clock from "@/components/apps/Clock";
import Settings from "@/components/apps/Settings";

const TASKBAR_APPS = [
  {
    id: 1,
    name: "Chrome",
    icon: "./images/apps/chrome.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://www.google.com/webhp?igu=1"}/>,
  },
  {
    id: 2,
    name: "Gmail",
    icon: "./images/apps/gmail.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://mail.google.com"}/>,
  },
  {
    id: 3,
    name: "Calendar",
    icon: "./images/apps/calendar.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://calendar.google.com"}/>,
  },
  {
    id: 4,
    name: "Photos",
    icon: "./images/apps/photos.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://photos.google.com"}/>,
  },
  {
    id: 5,
    name: "Docs",
    icon: "./images/apps/docs.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://docs.google.com"}/>,
  },
];

const STAR_MENU_DEFAULT_APPS = [
  {
    name: "Chrome",
    icon: "./images/apps/chrome.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://www.google.com/webhp?igu=1"}/>,
  },
  {
    name: "Gmail",
    icon: "./images/apps/gmail.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://mail.google.com"}/>,
  },
  {
    name: "Calendar",
    icon: "./images/apps/calendar.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://calendar.google.com"}/>,
  },
  {
    name: "Photos",
    icon: "./images/apps/photos.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://photos.google.com"}/>,
  },
  {
    name: "Docs",
    icon: "./images/apps/docs.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://docs.google.com"}/>,
  },
];

const STAR_MENU_APPS = [
  {
    name: "Chrome",
    icon: "./images/apps/chrome.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://www.google.com/webhp?igu=1"}/>,
  },
  {
    name: "Gmail",
    icon: "./images/apps/gmail.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://mail.google.com"}/>,
  },
  {
    name: "Calendar",
    icon: "./images/apps/calendar.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://calendar.google.com"}/>,
  },
  {
    name: "Photos",
    icon: "./images/apps/photos.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://photos.google.com"}/>,
  },
  {
    name: "Docs",
    icon: "./images/apps/docs.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://docs.google.com"}/>,
  },
  {
    name: "Calculator",
    icon: "./images/apps/calculator.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Calculator/>,
    defaultSize: {width: 320, height: 500}
  },
  {
    name: "Camera",
    icon: "./images/apps/camera.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Camera/>,
  },
  {
    name: "Clock",
    icon: "./images/apps/clock.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Clock/>,
  },
//   {
//     name: "Google Cloud",
//     icon: "./images/apps/cloud.svg",
//     iconShape: "non-circle",
//     link: "",
//   },
  {
    name: "Drive",
    icon: "./images/apps/drive.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://drive.google.com"}/>,
  },
  {
    name: "Earth",
    icon: "./images/apps/earth.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://earth.google.com"}/>,
  },
//   {
//     name: "Firebase",
//     icon: "./images/apps/firebase.svg",
//     iconShape: "non-circle",
//     link: "",
//     isMinimized: false,
//     render: <Browser link={"https://earth.google.com"}/>,
//   },
//   {
//     name: "Home",
//     icon: "./images/apps/home.svg",
//     iconShape: "non-circle",
//     link: "",
//     isMinimized: false,
//     render: <Browser link={"https://earth.google.com"}/>,
//   },
  {
    name: "Instagram",
    icon: "./images/apps/instagram.svg",
    iconShape: "non-circle",
    link: "",
  },
  {
    name: "Keep",
    icon: "./images/apps/keep.svg",
    iconShape: "non-circle",
    link: "",
  },
  {
    name: "Maps",
    icon: "./images/apps/maps.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://maps.google.com"}/>,
  },
  {
    name: "Meet",
    icon: "./images/apps/meet.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://meet.google.com"}/>,
  },
//   {
//     name: "One",
//     icon: "./images/apps/One.svg",
//     iconShape: "non-circle",
//     link: "",
//   },
//   {
//     name: "Microsoft Teams",
//     icon: "./images/apps/teams.svg",
//     iconShape: "non-circle",
//     link: "",
//   },
  {
    name: "Messenger",
    icon: "./images/apps/messenger.svg",
    iconShape: "non-circle",
    link: "",
  },
  {
    name: "Youtube",
    icon: "./images/apps/youtube.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://youtube.com"}/>,
  },
  {
    name: "Twitter",
    icon: "./images/apps/twitter.svg",
    iconShape: "non-circle",
    link: "",
  },
//   {
//     name: "Tag Manager",
//     icon: "./images/apps/tag-manager.svg",
//     iconShape: "non-circle",
//     link: "",
//   },
//   {
//     name: "Stadia",
//     icon: "./images/apps/stadia.svg",
//     iconShape: "non-circle",
//     link: "",
//   },
//   {
//     name: "Podcasts",
//     icon: "./images/apps/podcasts.svg",
//     iconShape: "non-circle",
//     link: "",
//   },
  {
    name: "Play Games",
    icon: "./images/apps/Play_Games.svg",
    iconShape: "non-circle",
    link: "",
  },
  {
    name: "Settings",
    icon: "./images/apps/Play_Games.svg",
    iconShape: "non-circle",
     render: <Settings/>,
  },
];

export { TASKBAR_APPS, STAR_MENU_DEFAULT_APPS, STAR_MENU_APPS };
