const TASKBAR_APPS = [
    {
        id: 1,
        name: "Chrome",
        icon: "./images/apps/chrome.svg",
        iconShape: "circle",
        link: "",
        isMinimized: false,
    },
    {
        id: 2,
        name: "Gmail",
        icon: "./images/apps/gmail.svg",
        iconShape: "non-circle",
        link: "",
        isMinimized: false,
    },
    {
        id: 3,
        name: "Calendar",
        icon: "./images/apps/calendar.svg",
        iconShape: "non-circle",
        link: "",
        isMinimized: false,
    },
    {
        id: 4,
        name: "Photos",
        icon: "./images/apps/photos.svg",
        iconShape: "non-circle",
        link: "",
        isMinimized: false,
    },
    {
        id: 5,
        name: "Docs",
        icon: "./images/apps/docs.svg",
        iconShape: "non-circle",
        link: "",
        isMinimized: false,
    },
];

const STAR_MENU_DEFAULT_APPS = [
    {
        name: "Chrome",
        icon: "./images/apps/chrome.svg",
        iconShape: "circle",
        link: "",
    },
    {
        name: "Gmail",
        icon: "./images/apps/gmail.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Calendar",
        icon: "./images/apps/calendar.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Photos",
        icon: "./images/apps/photos.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Docs",
        icon: "./images/apps/docs.svg",
        iconShape: "non-circle",
        link: "",
    },
];

const STAR_MENU_APPS = [
    {
        name: "Chrome",
        icon: "./images/apps/chrome.svg",
        iconShape: "circle",
        link: "",
    },
    {
        name: "Gmail",
        icon: "./images/apps/gmail.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Calendar",
        icon: "./images/apps/calendar.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Photos",
        icon: "./images/apps/photos.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Docs",
        icon: "./images/apps/docs.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Calculator",
        icon: "./images/apps/calculator.svg",
        iconShape: "circle",
        link: "",
    },
    {
        name: "Camera",
        icon: "./images/apps/camera.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Clock",
        icon: "./images/apps/clock.svg",
        iconShape: "circle",
        link: "",
    },
    {
        name: "Google Cloud",
        icon: "./images/apps/cloud.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Drive",
        icon: "./images/apps/drive.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Earth",
        icon: "./images/apps/earth.svg",
        iconShape: "circle",
        link: "",
    },
    {
        name: "Firebase",
        icon: "./images/apps/firebase.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Home",
        icon: "./images/apps/home.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Instagram",
        icon: "./images/apps/instagram.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Keep",
        icon: "./images/apps/keep.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Maps",
        icon: "./images/apps/maps.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Meet",
        icon: "./images/apps/meet.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "One",
        icon: "./images/apps/One.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Microsoft Teams",
        icon: "./images/apps/teams.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Messenger",
        icon: "./images/apps/messenger.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Youtube",
        icon: "./images/apps/youtube.svg",
        iconShape: "circle",
        link: "",
    },
    {
        name: "Twitter",
        icon: "./images/apps/twitter.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Tag Manager",
        icon: "./images/apps/tag-manager.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Stadia",
        icon: "./images/apps/stadia.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Podcasts",
        icon: "./images/apps/podcasts.svg",
        iconShape: "non-circle",
        link: "",
    },
    {
        name: "Play Games",
        icon: "./images/apps/Play_Games.svg",
        iconShape: "non-circle",
        link: "",
    },
];

export { TASKBAR_APPS, STAR_MENU_DEFAULT_APPS, STAR_MENU_APPS }